spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/teachgram-teste-2
    username: postgres
    password: 123
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true

